version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      # TODO: Work on this later
      # - setup_remote_docker:
      #     docker_layer_caching: true
      # - run:
      #     name: Build and push the docker image
      #     command: <UPDATE AND PUSH COMMAND>
      # - run:
      #     name: Deploy to Linode
      #     command: <DEPLOYMENT COMMAND TO LINODE WITH THE UPDATE SCRIPT>

workflows:
  sample:
    jobs:
      - build-and-test
