version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-and-build:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push the docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG
  deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
      - run:
          name: Deploy to Linode
          command: |
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
            ssh root@$SSH_HOST ./update.sh $DOCKERHUB_USERNAME $IMAGE_NAME $TAG

workflows:
  build-and-deploy:
    jobs:
      - test-and-build
      - deploy:
          requires:
          - test-and-build # only deploy once build job has completed
          filters:
            branches:
                only: main # only deploy on the main branch